package search

import (
	"fmt"
	"time"

	"github.com/starshine-sys/bcr"
)

func (c *commands) initExplanations(r *bcr.Router) (out []*bcr.Command) {
	// get explanations *that are marked as being able to be invoked as commands*
	explanations, err := c.DB.GetCmdExplanations()
	if err != nil {
		c.Sugar.Error("Error getting explanations:", err)
		return
	}

	for _, e := range explanations {
		// reassign the variable, otherwise we don't send the correct description
		e := e
		// add the command
		out = append(out, r.AddCommand(&bcr.Command{
			Name:    e.Name,
			Aliases: e.Aliases,

			Summary:     fmt.Sprintf("Autogenerated command that posts the explanation for `%v`", e.Name),
			Description: fmt.Sprintf("This command is an alias for `ex %v`.", e.Name),
			Hidden:      true,

			Cooldown: 1 * time.Second,
			Command: func(ctx *bcr.Context) (err error) {
				_, err = ctx.Send(e.Description, nil)
				return err
			},
		}))
	}

	// return all the commands
	return out
}
