package search

import (
	"fmt"
	"time"

	"github.com/starshine-sys/bcr"
)

func (c *commands) initExplanations(r *bcr.Router) {
	explanations, err := c.Db.GetCmdExplanations()
	if err != nil {
		c.Sugar.Error("Error getting explanations:", err)
		return
	}

	for _, e := range explanations {
		e := e
		r.AddCommand(&bcr.Command{
			Name:    e.Name,
			Aliases: e.Aliases,

			Summary:     fmt.Sprintf("Autogenerated command that posts the explanation for `%v`", e.Name),
			Description: fmt.Sprintf("This command is an alias for `%vex %v`.", r.Prefixes[0], e.Name),
			Hidden:      true,

			Cooldown: 1 * time.Second,
			Command: func(ctx *bcr.Context) (err error) {
				_, err = ctx.Send(e.Description, nil)
				return err
			},
		})
	}
}
